title: Surface Modeling for Engineering Applications
author: Marco Rossoni
copyright: "2026"
logo: ""

repository:
  url: https://github.com/mrc-rossoni/surface-book
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "notebook"

html:
  use_repository_button: true
  use_issues_button: true
  home_page_in_navbar: true

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - deflist
    - colon_fence
    - linkify
    - substitution
    - tasklist

sphinx:
  config:
    html_show_copyright: true
    html_extra_path:
      - _static
